[SERVICE]
    Flush         2
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Tag               ronflow.api
    Path              /ronflow/iis/ronflow-api/logs/*.log
    Parser            ronflow_plain
    Read_from_Head    true
    Refresh_Interval  5
    Skip_Long_Lines   On

[INPUT]
    Name              tail
    Tag               ronauth.api
    Path              /ronflow/iis/ronauth-api/logs/*.log
    Parser            ronflow_plain
    Read_from_Head    true
    Refresh_Interval  5
    Skip_Long_Lines   On

[INPUT]
    Name              tail
    Tag               ronflow.database-git-sync
    Path              /ronflow/iis/ronflow-api/app-data/database-git-sync.log
    Parser            ronflow_plain
    Read_from_Head    true
    Refresh_Interval  5
    Skip_Long_Lines   On

[INPUT]
    Name              tail
    Tag               ronflow.sample
    Path              /ronflow/sample-logs/*.log
    Parser            ronflow_plain
    Read_from_Head    true
    Refresh_Interval  5
    Skip_Long_Lines   On

[FILTER]
    Name    modify
    Match   ronflow.api
    Add     service.name ronflow-api
    Add     service.environment localhost

[FILTER]
    Name    modify
    Match   ronauth.api
    Add     service.name ronauth-api
    Add     service.environment localhost

[FILTER]
    Name    modify
    Match   ronflow.database-git-sync
    Add     service.name database-git-sync
    Add     service.environment localhost

[FILTER]
    Name    modify
    Match   ronflow.sample
    Add     service.name ronflow-sample
    Add     service.environment localhost

[FILTER]
    Name    lua
    Match   *
    script  /fluent-bit/etc/redact.lua
    call    redact

[OUTPUT]
    Name                  opensearch
    Match                 *
    Host                  opensearch
    Port                  9200
    Index                 ronflow-logs
    Suppress_Type_Name    On
    Logstash_Format       On
    Logstash_Prefix       ronflow-logs
    Replace_Dots          On
    Retry_Limit           10
